ci: travis
review_rules:
  "/":
    maintainers:
      - sassom
      - smatejina
    reviews_needed: 1

  "/.gatekeeper.yml":
    maintainers:
      - sassom
      - smatejina
    reviews_needed: 2

